package com.example.finsentinel.model.enums;

/**
 * Typed event names for agent autonomy and replay workflows.
 */
public enum AgentEventType {
    CHAT_SESSION_STARTED,
    CHAT_MESSAGE_PERSISTED,
    CHAT_CONTEXT_COMPACTED,
    CHAT_STREAM_ERROR,

    TRADING_MODE_SWITCHED,
    TRADE_OPERATION_STAGED,
    TRADE_COMMIT_CREATED,
    TRADE_COMMIT_EXECUTED,

    BRAIN_STRATEGY_UPDATED,
    BRAIN_EMOTION_UPDATED,

    SCHEDULE_CREATED,
    SCHEDULE_UPDATED,
    SCHEDULE_DELETED,
    SCHEDULE_EXECUTED,
    SCHEDULE_FAILED,

    HEARTBEAT_TICK,
    HEARTBEAT_ALERT,

    // OKX Crypto Events
    OKX_POSITION_OPENED,
    OKX_POSITION_CLOSED,
    OKX_RISK_ALERT,
    OKX_HEALTH_CHECK_RUN
}
